<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="4" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Verify the appdirect home page]]>
    </line>
    <line>
      <![CDATA[Verified the login page]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="17335" started-at="2017-04-06T12:06:57Z" finished-at="2017-04-06T12:07:14Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="17335" started-at="2017-04-06T12:06:57Z" finished-at="2017-04-06T12:07:14Z">
      <class name="com.appdirect.nitya.TestClass">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:com.appdirect.nitya.TestClass@475530b9]" name="openBrowser" duration-ms="17196" started-at="2017-04-06T17:36:57Z" finished-at="2017-04-06T17:37:14Z">
          <reporter-output>
            <line>
              <![CDATA[Verify the appdirect home page]]>
            </line>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="openHomePage()[pri:0, instance:com.appdirect.nitya.TestClass@475530b9]" name="openHomePage" duration-ms="115" started-at="2017-04-06T17:37:14Z" depends-on-methods="com.appdirect.nitya.TestClass.openBrowser" finished-at="2017-04-06T17:37:14Z">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.LoginPage.LoginPage.loginPageStatus(LoginPage.java:46)
	at com.appdirect.nitya.TestClass.openHomePage(TestClass.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[Verified the login page]]>
            </line>
          </reporter-output>
        </test-method> <!-- openHomePage -->
        <test-method status="SKIP" signature="openLoginPage()[pri:0, instance:com.appdirect.nitya.TestClass@475530b9]" name="openLoginPage" duration-ms="0" started-at="2017-04-06T17:37:14Z" depends-on-methods="com.appdirect.nitya.TestClass.openHomePage" finished-at="2017-04-06T17:37:14Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestClass.openLoginPage()[pri:0, instance:com.appdirect.nitya.TestClass@475530b9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestClass.openLoginPage()[pri:0, instance:com.appdirect.nitya.TestClass@475530b9] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openLoginPage -->
        <test-method status="SKIP" signature="openSignUpPage()[pri:0, instance:com.appdirect.nitya.TestClass@475530b9]" name="openSignUpPage" duration-ms="0" started-at="2017-04-06T17:37:14Z" depends-on-methods="com.appdirect.nitya.TestClass.openLoginPage" finished-at="2017-04-06T17:37:14Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestClass.openSignUpPage()[pri:0, instance:com.appdirect.nitya.TestClass@475530b9] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestClass.openSignUpPage()[pri:0, instance:com.appdirect.nitya.TestClass@475530b9] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openSignUpPage -->
      </class> <!-- com.appdirect.nitya.TestClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
